# Generated by Django 4.0.3 on 2022-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_adres_remove_przepisane_leki_recepta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My blog!', max_length=255),
        ),
    ]
